version: '3'

services:
  ors-classic-maps:
    container_name: dors_client
    image: ors-classic-maps:dors
    ports:
      - 8035:3035
      - 3005:3005
    build:
      context: .
    volumes:
      - ./app:/ors-classic-maps/app
      - ./Gruntfile.default.js:/ors-classic-maps/Gruntfile.js
    entrypoint: ["/ors-classic-maps/node_modules/grunt-cli/bin/grunt","-b", "/ors-classic-maps"]
    command: "ors"

networks:
  default:
    external:
      name: heigit_dors_network
